### ISSUE TITLE
Setup advanced seed for Prisma DB

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#100]
*As a* dev
*I want to* have a database seed
*In order to* have mock data for display and user handling test

***
**Requirements**
* Have mock data for all entities

**Dependencies**
* #77

**Task Completion Checklist**
- [x] Have mock data for Customer
- [x] Have mock data for OrderLine
- [x] Have mock data for Order
- [x] Have mock data for Purchase
