### ISSUE TITLE
Prisma Composite Primary Keys

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#103]
*As a* db engineer
*I want to* develop composite prisma primary keys
*In order to* mantain data consistency

***
**Requirements**
* Prisma schema should only accept valid input in the relation db
* Composite keys on Stand
* Composite keys on Stock

**Dependencies**
* #76 

**Task Completion Checklist**
- [ ] Setup new schema
- [ ] Validate new schema
- [ ] Port seed scripts
- [ ] Port current scripts that call prisma

**Comment by josalhor** [comment]
Won't fix in the specified time frame of the project
