### ISSUE TITLE
Merge User Schema and Domain Schema

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#104]
*As a* dev
*I want to* merge the user schema and farmer/customer schema
*In order to* have a single unified user storage point and a unified schema

***
**Requirements**
* Unify User Schema and Domain schema so email, password, name etal are only stored once

**Dependencies**
* #98 
* #76 

**Task Completion Checklist**
- [x] Setup new schema
- [x] Validate new schema
- [x] Port seed scripts
- [x] Port current scripts that call prisma
