### ISSUE TITLE
Consult info of the market

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#12]
# Overview
As a consumer I want to be able to consult info of the market

# Features
- [ ] See farmers of a market
- [ ] See the description of the farmers of a market
- [ ] See the location of the market
- [ ] See the schedule of the market

# Useful links
* Visual design
* Api definition
* Other links...

**Comment by josalhor** [comment]
Duplicated
