### ISSUE TITLE
Get Push Notifications

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#150]
# Overview
Get Push Notifications working on the client

# Requirements/Features/Workflow
- [ ] Service Worker on Browser
- [ ] Web push dependency
- [ ] Subscribe example
- [ ] Endpoint with push
- [ ] Tested
- [ ] Deployed

# Useful links
* https://stackoverflow.com/questions/67761327/how-to-add-push-notification-using-next-pwa
* https://github.com/shadowwalker/next-pwa/tree/master/examples/custom-worker
* https://github.com/shadowwalker/next-pwa/blob/master/examples/web-push/pages/api/notification.js
* https://stackoverflow.com/questions/64494398/next-pwa-not-working-on-production-server-such-as-nginx
