### ISSUE TITLE
Sign up a customer

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#19]
*As a* customer
*I want to* be able to sign up
*In order to* access the platform

***
**Requirements**
* Access credentials (Email & Password)
* User data (Full Name, Gender, Age, Email)
* Redirect to main page

**Task Completion Checklist**
- [ ] Completed Sign up flow on Mobile
- [ ] Test Sign up flow on Mobile
- [ ] Screenshot on Mobile
- [ ] Completed Sign up flow on Web
- [ ] Test Sign up flow on Web
- [ ] Screenshot on Web
