### ISSUE TITLE
Manage farmer's markets

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/lo-mercat#3]
# Overview
*As a* SuperAdmin
*I want to* Manage markets
*In order to* edit infomation about it, join farmer's stand,...

**Requirements**
- [ ]  #33 
- [ ]  #34 
- [ ]  #35 
- [ ]  #46 
- [ ]  #47 

**Task Completion Checklist**
- [ ] Completed flow on Mobile
- [ ] Test flow on Mobile
- [ ] Screenshot on Mobile
- [ ] Completed flow on Web
- [ ] Test flow on Web
- [ ] Screenshot on Web
