### ISSUE TITLE
Create a deploy configuration

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/lo-mercat#56]
*As a* developer
*I want to* create a deploy configuration
*In order to* handle more efficiently my deploy flow

***
**Requirements**
* Has to deploy the app into the UdL server (**Waiting for the access**)
* Has to be done using github actions
* Has to be executed when a merge from dev to main is completed
* Has to provide a containerized solution
* Credentials need to be stored as Github secrets or enviroment variables, **no hardcoded creds**

**Development tasks:**
- [x] #106
- [x] #78  (adminjs)
- [x] #75  (lo-mercat-db) 
- [x] #86 
- [x] #87

**Dependencies**
* #69 
* #70 

**Task Completion Checklist**
- [x] I can access the app from my personal laptop conecting to the UdL server (NOT DONE)
- [x] I can use docker to deploy the app in my laptop

**Comment by JoanPalau** [comment]
Access to the UdL server has not been granted. 
Moving the final configuration for the server to a seperate task as it has this external dependency.
