### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by ColoDidac** [JoanPalau/lo-mercat#63]
*As a* User
*I want to* see a landing page
*In order to* get introduced to the page

***
**Requirements**
* Should match the visual components designed
* Should be done following the guidelines shown in the different workshops

**Dependencies**
- [x] React Workshop ( @JoanPalau - Completed 10/10/2022)
- [x] Atomic Design Workshop ( @JoanPalau - Completed 10/10/2022)
- [x] Styled components Workshop ( @JoanPalau - Completed 17/10/2022)

**Developer tasks**
- [x] Carrusel text - Josep Maria
- [x] Sign up / Login footer - Didac
- [x] Our_service component - Joan
- [x] About_us component - Cristian
- [x] Footer - Didac
- [x] Landing Page - All together

**Task Completion Checklist**
- [x] Completed flow on Mobile
- [x] Test flow on Mobile
- [x] Screenshot on Mobile
- [x] Completed flow on Web
- [x] Test flow on Web
- [x] Screenshot on Web

**Comment by JoanPalau** [comment]
Completed the task, will work on an improved version of this landing page for desktop during the next sprint
