### ISSUE TITLE
Home page for Customer

### ISSUE THREAD

**Issue by ColoDidac** [JoanPalau/lo-mercat#65]
*As a* Customer
*I want to* see a main page
*In order to* get available all the capabilities of the page

***
**Requirements**
* Be Logged in the page

**Dependencies**
* #22 

**Task Completion Checklist**
- [x] Completed flow on Mobile
- [ ] Test flow on Mobile
- [x] Screenshot on Mobile
- [x] Completed flow on Web
- [x] Test flow on Web
- [x] Screenshot on Web

**Comment by JoanPalau** [comment]
Completed a basic home page that enables navigation for the customer. Will need to improve the look and feel and items displayed, but it's functional.
