### ISSUE TITLE
Create initial project setup

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/lo-mercat#69]
*As a* developer
*I want to* create the initial project stucture
*In order to* setup the basic infrastructure for the rest of the team

***
**Requirements**
* The chosen technology is next.js
* May generate by default a PWA

**Dependencies**
* Selecting a framework/technology to start the development.

**Task Completion Checklist**
- [x] Completed flow on Mobile
- [x] Test flow on Mobile
- [x] Completed flow on Web
- [x] Test flow on Web

**Comment by JoanPalau** [comment]
Screnshoots are not needed as this is only the basic setup.
A demo has been shown to the rest of the team in order to be all in the same page
