### ISSUE TITLE
Create Admin Panel

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#74]
*As an* admin
*I want to* acces an admin panel
*In order to* manipulate data entities

***
**Requirements**
* Create setup with Express Framework
* Create setup with AdminJs-Express
* Create setup with AdminJs-Prisma
* Setup admin page with AdminJS
* Setup entities on AdminJS
* Setup Login Page with AdminJS

**Dependencies**
* #75 
* #76 

**Task Completion Checklist**
- [x] Completed backend setup
- [x] Completed requirements web
- [x] Test flow on Web
- [x] Screenshot on Web
