### ISSUE TITLE
Setup Docker DB

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#75]
*As a* dev
*I want to* deploy a database
*In order to* make data persistent

***
**Requirements**
* Setup Docker PostgreSQL Database
* Document the steps in this issue so it can be replicated

**Task Completion Checklist**
- [x] Setup Docker DB
- [x] Run and Test Docker DB
- [x] Deploy Docker DB

**Comment by josalhor** [comment]
```
sudo docker pull postgres
docker run --name lo-mercat-db -e POSTGRES_PASSWORD=lo-mercat-ps -d -p 5432:5432 postgres
```
