### ISSUE TITLE
Setup Prisma DB

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#76]
*As a* dev
*I want to* setup the Prisma DB
*In order to* manage the schema and be able to make queries

***
**Requirements**
* Be able to make calls from NextJS to the DB with Prisma
* Have Prisma DB schema available
* Have Prisma Deployed

**Task Completion Checklist**
- [x] Install prisma requirements
- [x] Map the UML schema to the Prisma Schema
- [x] Run the migrations of Prisma
- [x] Integrate Prisma with Next
