### ISSUE TITLE
Setup seed for Prisma DB

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#77]
*As a* dev
*I want to* have a database seed
*In order to* have mock data for displau

***
**Requirements**
* Have mock data for all entities

**Dependencies**
* #76 

**Task Completion Checklist**
- [x] Have mock data for Market
- [x] Have mock data for Farmer
- [x] Have mock data for User
- [x] Have mock data for Product
- [x] Have mock data for Stock
- [x] Have mock data for Stand
