### ISSUE TITLE
Setup AdminJS panel

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#78]
*As a* dev
*I want to* have access to the AdminJS Panel
*In order to* manage data from the DB

***
**Requirements**
* Have access to AdminJS DB

**Dependencies**
* #76 

**Task Completion Checklist**
- [x] Create setup with Express Framework
- [x] Create setup with AdminJs-Express
- [x] Create setup with AdminJs-Prisma
- [x] Setup admin page with AdminJS
- [x] Setup admin page with AdminJS
- [x] Setup entities on AdminJS
