### ISSUE TITLE
Manage costumers

### ISSUE THREAD

**Issue by JoanPalau** [JoanPalau/lo-mercat#8]
# Overview
*As a* Admin
*I want to* Manage costumers
*In order to* delete, ban a costumer

**Requirements**
- [ ]  #36
- [ ]  #37

**Task Completion Checklist**
- [ ] Completed flow on Mobile
- [ ] Test flow on Mobile
- [ ] Screenshot on Mobile
- [ ] Completed flow on Web
- [ ] Test flow on Web
- [ ] Screenshot on Web
