### ISSUE TITLE
AdminJS integration into application

### ISSUE THREAD

**Issue by josalhor** [JoanPalau/lo-mercat#99]
*As a* super user/admin
*I want to* access the AdminJS panel
*In order to* manage the DB

***
**Requirements**
* Setup Login Page on AdminJS if required
* Connect AdminJS login with product login
* Connect AdminJS Panel with product interface

**Dependencies**
* #78 

**Task Completion Checklist**
- [ ] Setup Login Page with AdminJS
- [ ] Completed flow on Web
- [ ] Test flow on Web

**Comment by josalhor** [comment]
Closed as won't fix and/or future work
